### ISSUE TITLE
In Bookstack uploaded images are not found

### ISSUE THREAD

**Issue by ThomasK1966** [tiredofit/docker-bookstack#4]
I want to include in my Bookstack [www.thomass-itwiki.de](https://www.thomass-itwiki.de) some images.
But they are not found, when open the site with it.
The upload works fine.
The uploaded images are then located in the following paths inside the container:
/data/storage/uploads/images/gallery/...
/www/bookstack/storage/uploads/images/gallery...

On my site it looks like this:
[https://www.thomass-itwiki.de/books/raspberrymatic/page/smart-home-wandtaster-2-fach-wrcc2](https://www.thomass-itwiki.de/books/raspberrymatic/page/smart-home-wandtaster-2-fach-wrcc2)
When you click on the image error "404 Not Found" with this url:
[https://www.thomass-itwiki.de/uploads/images/gallery/2024-04/155342-hmipwandtaster-flach-l-600x600.jpg](https://www.thomass-itwiki.de/uploads/images/gallery/2024-04/155342-hmipwandtaster-flach-l-600x600.jpg)

I don't know if this is a bug or if I need to configure something somewhere.

### Environment

- Image version / tag:  latest_php8.2
- Host OS: Arch Linux

**Comment by jozefrebjak** [comment]
@tiredofit I have the same problem. There is problem with images.
